---
- name: checks if resolver is working properly (issues with some VBox/Host OS combinations)
  command: host -t A ansible.cc
  register: ns
  ignore_errors: yes

- name: pushes new resolver configuration is resolver fails
  sudo: yes
  lineinfile: regexp="^nameserver " line="nameserver 8.8.8.8" dest=/etc/resolv.conf
  when: ns|failed

- name: checks if resolver is working properly with new nameserver
  command: host -t A ansible.cc

- name: make sure the system encoding is {{ locale }}
  sudo: yes
  template: src=locale dest=/etc/default/locale
            owner=root group=root mode=644

- name: ensure apt cache is up to date
  sudo: yes
  apt: update_cache=yes

- name: install {{ item }} pkgs
  sudo: yes
  apt: pkg={{ item }}
  with_items: packages

- name: create users
  sudo: yes
  user: name={{ item.name }} home={{ item.home }} comment="{{ item.comment }}" generate_ssh_key=yes state=present
  with_items: users

- name: update access to users directory
  sudo: yes
  file: state=directory mode=755 owner={{ item.name }} group={{ item.name }} name={{ item.home }}
  with_items: users

- name: update users groups
  sudo: yes
  user: name={{ item.name }} groups={{ item.groups }}
  with_items: users

- name: app_prepare | Create apps users path
  sudo: yes
  file: state=directory path={{ projects_directory }}
